### ISSUE TITLE
Component BOM unavailable

### ISSUE THREAD

**Issue by edacraneo** [tianfeng33/O-MVS#1]
Hello,
Thanks for your great job, I'm trying to find the material available in the boom file but some products are unavailable. Would it be possible to have up-to-date BOM files? for example, the STEF04spur component cannot be found on the webt, is there an alternative? 

Thank you so much 

Regards

**Comment by tianfeng33** [comment]
Hi,  it might just be the labeling.  https://www.digikey.ca/en/products/detail/stmicroelectronics/STEF4SPUR/4383954?s=N4IgTCBcDaIMoBcCmAzALCAugXyA

It is probably an stef4s now and not 04. That link should work and I will update the bom later today.

**Comment by edacraneo** [comment]
Thank you Tianfeng33 for the link but 0 in stock and 28 Weeks for new stock.. 
Not possible to use another component ? identical please ?

Than you a lot

Regards

**Comment by tianfeng33** [comment]
No, just use that since it is not EOL. Arrow has stock.  You just needed to google it. https://www.arrow.com/en/products/stef4spur/stmicroelectronics

**Comment by edacraneo** [comment]
yes indeed I was looking for the components especially in France, Thank you again for your help.
Have a nice day
